# Spring properties
spring:
  application:
    name: CaasDashboard  # Identify this application
  main:
    allow-bean-definition-overriding: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  freemarker:
    template-loader-path: classpath:/templates/


##INFRA_ADMIN Settings
project:
  name: paasta-caas-dashboard
  artifactId: paasta-caas-dashboard
  description: paasta-caas-dashboard
info:
  app:
    encoding: Encoding - UTF-8
  java:
    source: Source - java ver
    target: Instance1 - Java ver
  spring:
    profiles: ${spring.profiles.active:default}
  build:
    name: ${project.name}
    artifact: ${project.artifactId}
    description: ${project.description}


management:
  security:
    enabled: false

# HTTP Server
server:
  port: ${PORT:8091}   # HTTP (Tomcat) port

---
spring:
  profiles: local
datasource:
  caas:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://
    username:
    password:
jpa:
  hibernate.ddl-auto: update
  show-sql: true
  database-platform: org.hibernate.dialect.MySQL5InnoDBDialect



---
spring:
  profiles: dev
